version: "3"

services:
  auth-service:
    build: ./auth-service
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=auth_service_secret_key
      - JWT_EXPIRATION=300
    volumes:
      - ./auth-service:/app
      - /app/node_modules
    depends_on:
      - redis

  location-service:
    build: ./location-service
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./location-service:/app
      - /app/node_modules
    depends_on:
      - redis

  realtime-service:
    build: ./realtime-service
    ports:
      - "3003:3000"
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - LOCATION_SERVICE_URL=http://location-service:3000
      - AUTH_SERVICE_URL=http://auth-service:3000
    volumes:
      - ./realtime-service:/app
      - /app/node_modules
    depends_on:
      - redis
      - auth-service
      - location-service

  gateway-service:
    build: ./gateway-service-bff
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - AUTH_SERVICE_URL=http://auth-service:3000
      - LOCATION_SERVICE_URL=http://location-service:3000
      - REALTIME_SERVICE_URL=http://realtime-service:3000
    volumes:
      - ./gateway-service-bff:/app
      - /app/node_modules
    depends_on:
      - auth-service
      - location-service
      - realtime-service

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
  pnpm-store:
    driver: local
